version: '3'
services:
  kaiburr-nginx:
    container_name: kaiburr-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - kaiburr-ui

  kaiburr-mongodb:
    container_name: kaiburr-mongodb
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  kaiburr-backend:
    container_name: kaiburr-backend-by-anurag
    image: kaiburr-server:latest
    expose:
      - 8080
    depends_on:
      - kaiburr-mongodb

  kaiburr-ui:
    container_name: kaiburr-ui-by-anurag
    image: kaiburr-ui:latest
    expose:
      - 4200
    depends_on:
      - kaiburr-backend
